# Generated by Django 4.1 on 2022-10-19 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='disease',
            new_name='message',
        ),
    ]
